### ISSUE TITLE
Make fields with default values optional

### ISSUE THREAD

**Issue by kalcicd** [Kalissaac/prisma-typegen#1]
Hey @Kalissaac !
I stumbled upon this package the other day, and it fits my use case very well, with only one small hang up. I'm using prisma-typegen to create a library of interfaces that are imported by several micro-services. I have several fields in my schema.prisma file (such as `id` and `created_at`) that have default values, usually a database function. Because I'm relying on database functions instead TS code to populate these fields, I think it would make sense to have prisma-typegen only mark fields without a default value as being required. 

I've already implemented a quick fix for this:
[This](https://github.com/Kalissaac/prisma-typegen/blob/9fcfbbe8e28cd9a11e38953cdb110970e109720c/src/generateTypes.ts#L63) line should instead read `required: f.isRequired && !f.hasDefaultValue,`.

I could see enabling this behavior as an option if you're assigning the generated interface to a row already in the database, but for a case like mine where I'm assigning the interface to data get to be inserted, this change makes a lot of sense.

Thanks for reading!

**Comment by Kalissaac** [comment]
Hey @kalcicd thanks for opening this issue!

I initially created this package to use the interfaces as you mentioned in the first instance, which is to give types to data received from the database. I'd definitely be interested in adding functionality for your use case, my only request is that we would put it behind a flag when generating so that the default functionality remains the same.

If you'd like to create a PR for this then please go ahead, otherwise I'll create one in the next few days when I get a chance.

**Comment by kalcicd** [comment]
Will do. I think there might be a few other differences between an interface applied before insertion and one applied after selection that could be addressed in the same feature PR. One such example that comes to mind would be the mapping of the Prisma `DateTime` type. The Prisma client supports inserting a `DateTime` field as either a native `Date` type or an ISO 8601 compliant `string`. Additionally, I don't think fields with the `@relation` tag should be included in the generated interface since that validation can only be performed when attempting to insert a row.

Perhaps the `--insertionModel` flag could be used to enable these options?

**Comment by Kalissaac** [comment]
Sounds good to me!

**Comment by kalcicd** [comment]
Addressed in PR #2
